---
- name: Ensure Desktop parent directories exist
  ansible.builtin.file:
    path: "{{ xdg_config }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - klassy
    - Kvantum
    - kwin
    - plasma-workspace

- name: Force-symlink Desktop Configuration Files
  ansible.builtin.file:
    src: "{{ repo_system }}/desktop/{{ item.folder }}/{{ item.file }}"
    dest: "{{ xdg_config }}/{{ item.dest | default(item.file) }}"
    state: link
    force: yes
  loop:
    # KWin
    - { folder: "kwin", file: "kwinrc" }
    - { folder: "kwin", file: "kwinrulesrc" }
    # Klassy
    - { folder: "klassy", file: "klassyrc" }
    - { folder: "klassy", file: "windecopresetsrc" }
    # Plasma
    - { folder: "plasma", file: "breezerc" }
    - { folder: "plasma", file: "kdeglobals" }
    - { folder: "plasma", file: "kglobalshortcutsrc" }
    - { folder: "plasma", file: "plasmarc" }
    - { folder: "plasma", file: "plasmashellrc" }

- name: Force-symlink entire Kvantum theme directory
  ansible.builtin.file:
    src: "{{ repo_system }}/desktop/Kvantum"
    dest: "{{ xdg_config }}/Kvantum"
    state: link
    force: yes