# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: workstation
description: "Bazzite base, KDE Desktop, GTK apps, Distrobox utilities"

base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: theme/klassy
        destination: /etc/skel/.config/klassy

      - source: scripts
        destination: /usr/bin
      - source: distrobox
        destination: /etc/distrobox


  - type: systemd
    user:
      enabled:
        - setup-distrobox.service

  - type: gschema-overrides

  - type: dnf
    repos:
      files:
        add:
          - https://download.opensuse.org/repositories/home:paulmcauley/Fedora_44/home:paulmcauley.repo
      copr:
        enable:
          - infinality/kwin-effects-better-blur-dx
          - atim/starship

    install:
      packages:
        - meson
        - sassc
        - gtk-murrine-engine
        - kitty
        - nautilus
        - gnome-disks
        - zsh
        - wl-clipboard
        - kde-connect
        - sbsigntools
        - klassy
        - kwin-effects-better-blur-dx
        - kwin-effects-better-blur-dx-x11
        - distrobox
        - starship

  - type: default-flatpaks
    configurations:
      - scope: user
        notify: true
        install:
          - app.zen_browser.zen
          - it.mijorus.gearlever
          - com.github.tchx84.Flatseal
          - org.gnome.font-viewer
          - org.onlyoffice.desktopeditors
          - com.obsproject.Studio
          - org.gnome.Papers
          - org.gnome.Loupe
          - org.videolan.VLC
          - org.freedesktop.Piper
          - org.fedoraproject.MediaWriter
          - io.missioncenter.MissionCenter
          - md.obsidian.Obsidian
          - org.localsend.localsend_app
          - dev.vencord.Vesktop
          - com.vscodium.codium
          - com.ranfdev.DistroShelf

  - type: fonts
    fonts:
      nerd-fonts:               
        - JetBrainsMono
      google-fonts:              
        - Inter