# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: workstation
description: "Base: Bazzite | Desktop: KDE | Purpose: Dev, Office, Gaming"

base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: gschema-overrides
    include:
      - zz1-window-buttons.gschema.override

  - type: dnf
    repos:
      files:
        add:
          - https://download.opensuse.org/repositories/home:paulmcauley/Fedora_44/home:paulmcauley.repo
          - https://download.opensuse.org/repositories/home:luisbocanegra/Fedora_44/home:luisbocanegra.repo
          - https://download.docker.com/linux/fedora/docker-ce.repo
          - protonvpn.repo
          - vscode.repo
          - netbird.repo

      copr:
        enable:
          - infinality/kwin-effects-better-blur-dx
          - atim/starship
          - lionheartp/Hyprland
          - lihaohong/yazi
          - jdxcode/mise
          - aquacash5/nerd-fonts
          - deltacopy/darkly
          - vcalles/wavetask

    install:
      packages:
        # Utilities
        - yazi
        - eza
        - zoxide
        - bat
        - ripgrep
        - fd-find
        - fzf
        - tldr
        - btop
        - gh
        - jq
        - yq
        - unzip
        - wget
        - curl
        - git
        - kitty
        - starship
        - zsh
        - distrobox
        - mise

        # The reason VSCode is here instead of the flatpak app section
        # is because a flatpak doesn't have system access,
        # since i want to have only one tool for modifying every file
        # i need to have vscode to have full system access to modify stuff like
        # /etc or similar locations
        - code

        # Virtual Machines
        - qemu-kvm
        - libvirt
        - virt-install
        - edk2-ovmf
        - swtpm
        - qemu-img
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        - freerdp
        - winboat-0.9.0-x86_64.rpm

        # System
        - sbsigntools
        - wl-clipboard

        # Fonts
        - rsms-inter-fonts
        - jet-brains-mono-nerd-fonts

        # KDE Stuff
        - kvantum
        - nwg-look
        - kde-partitionmanager
        - kde-connect
        - klassy
        - kwin-effects-better-blur-dx
        - kwin-effects-better-blur-dx-x11
        - plasma-panel-colorizer
        - darkly
        - plasma-discover
        - plasma-discover-rpm-ostree
        - plasma-discover-flatpak

    remove:
      packages:
        #KDE Debloating
        - kde-gtk-config
        - konsole
        - kwrite
        - kate
        - filelight
        - krfb
        - krdc
        - bazaar
        - PackageKit
        - PackageKit-glib
        - plasma-discover-packagekit # if it got pulled in

        # Bazzite Debloating
        - waydroid
        - cage
        - wlr-randr
        - lato-fonts
        - fira-code-fonts
        - nerd-fonts
        - plasma-oxygen
        - oxygen-icon-theme
        - gnome-disk-utility
        - stress-ng
        - powerbuttond
        - sdgyrodsu
        - duf
        - gum
        - jupiter-fan-control
        - jupiter-hw-support-btrfs
        - jupiter-sd-mounting-btrfs
        - steamdeck-dsp
        - steamdeck-kde-presets-desktop
        - steamdeck-backgrounds
        - galileo-mura
        - bazzite-portal
        - cockpit-networkmanager
        - cockpit-podman
        - cockpit-selinux
        - cockpit-system
        - cockpit-files
        - cockpit-storaged
        - gmodpatchtool
        - vpower
        - steamos-manager-powerstation
        - steamos-manager-powerstation-gamescope-session-plus
        - steam-notif-daemon
        - inputplumber
        - gamescope-session-ogui-steam
        - ds-inhibit2
        - khelpcenter
        - ryzenadj

  - type: script
    scripts:
      - setup_shell.sh
    snippets:
      - chmod +x /etc/bluebuild/*
      - dnf install -y --setopt=tsflags=noscripts proton-vpn-gnome-desktop
      - dnf install -y --setopt=tsflags=noscripts netbird netbird-ui gtk4 webkitgtk6.0 xdg-utils

      # === VM ===
      # TPM directory for windows machines
      - mkdir -p /var/lib/swtpm-localca
      - chown tss:tss /var/lib/swtpm-localca
      - restorecon -Rv /var/lib/libvirt /var/log/libvirt /var/lib/swtpm-localca 2>/dev/null || true

  - type: kargs
    kargs:
      - kvm.ignore_msrs=1
      - kvm.report_ignored_msrs=0

  - type: systemd
    system:
      enabled:
        - libvirtd
        - docker
