# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: workstation
description: "Bazzite base, KDE Desktop, GTK apps, Distrobox utilities"

base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

      - source: scripts
        destination: /etc/bluebuild/scripts

  - type: gschema-overrides
    include:
      - zz1-window-buttons.gschema.override

  - type: dnf
    repos:
      files:
        add:
          - https://download.opensuse.org/repositories/home:paulmcauley/Fedora_44/home:paulmcauley.repo
          - https://download.opensuse.org/repositories/home:luisbocanegra/Fedora_44/home:luisbocanegra.repo
          
      copr:
        enable:
          - infinality/kwin-effects-better-blur-dx
          - atim/starship
          - lionheartp/Hyprland
          - lihaohong/yazi

    install:
      packages:
        # Modern utilities
        - fastfetch
        - yazi
        - eza
        - zoxide
        - bat
        - ripgrep
        - fd-find
        - fzf
        - tldr
        - btop
        - gh 
        - jq
        - yq
        - unzip
        - wget
        - curl
        - git

        
        - kvantum
        - kitty
        - nwg-look
        - kde-partitionmanager 
        - zsh
        - wl-clipboard
        - kde-connect
        - sbsigntools
        - klassy
        - kwin-effects-better-blur-dx
        - kwin-effects-better-blur-dx-x11
        - distrobox
        - starship
        - plasma-panel-colorizer

    remove:
      packages:
        #KDE Debloating
        - kde-gtk-config
        - konsole
        - kwrite
        - kate
        - filelight
        - krfb
        - krdc
        
        # Bazzite Debloating
        - waydroid
        - cage
        - wlr-randr
        - lato-fonts
        - fira-code-fonts
        - nerd-fonts
        - plasma-oxygen
        - oxygen-icon-theme
        - gnome-disk-utility
        - fastfetch
        - stress-ng
        - powerbuttond
        - sdgyrodsu
        - btop
        - duf
        - gum
        - jupiter-fan-control
        - jupiter-hw-support-btrfs
        - jupiter-sd-mounting-btrfs
        - steamdeck-dsp
        - steamdeck-kde-presets-desktop
        - galileo-mura
        - vpower
        - steamos-manager-powerstation
        - steamos-manager-powerstation-gamescope-session-plus
        - steam-notif-daemon
        - inputplumber
        - gamescope-session-ogui-steam
        - ds-inhibit

  - type: default-flatpaks
    configurations:
      - scope: user
        install:
          # Desktop Essentials
          - app.zen_browser.zen # Browser
          - org.kde.kcalc # Calculator
          - org.onlyoffice.desktopeditors # Office Suite
          - com.obsproject.Studio # Video Recording
          - org.kde.okular # PDF Reader
          - org.kde.gwenview # Image Viewer
          - org.videolan.VLC # Audio & Video Player
          - md.obsidian.Obsidian # Notes
          - org.localsend.localsend_app # File Sharing
          - dev.vencord.Vesktop # Discord
          - com.vscodium.codium # Editor

          # Comptaibility
          - it.mijorus.gearlever # AppImage handling
          - com.ranfdev.DistroShelf # Distrobox handling
          - com.github.tchx84.Flatseal # Flatpak permissions
          - org.fedoraproject.MediaWriter # ISO Burner
          - org.freedesktop.Piper # Logitech 

  - type: fonts
    fonts:
      nerd-fonts:               
        - JetBrainsMono
      google-fonts:              
        - Inter

  - type: script
    scripts:
      - setup_shell.sh