---
- name: Ensure Appearance directories exist
  ansible.builtin.file:
    path: "{{ xdg_data }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - aurorae/themes
    - color-schemes
    - icons
    - plasma/desktoptheme
    - plasma/look-and-feel
    - wallpapers

- name: Symlink Aurorae Themes
  ansible.builtin.file:
    src: "{{ repo_system }}/appearance/aurorae/themes"
    dest: "{{ xdg_data }}/aurorae/themes"
    state: link
    force: yes

- name: Symlink Color Schemes
  ansible.builtin.file:
    src: "{{ repo_system }}/appearance/color-schemes"
    dest: "{{ xdg_data }}/color-schemes"
    state: link
    force: yes

- name: Symlink Icons & Cursors
  ansible.builtin.file:
    src: "{{ repo_system }}/appearance/{{ item }}"
    dest: "{{ xdg_data }}/icons/{{ item }}"
    state: link
    force: yes
  loop:
    - icons
    - cursors

- name: Symlink GTK Configurations
  ansible.builtin.file:
    src: "{{ repo_system }}/appearance/gtk/{{ item }}"
    dest: "{{ xdg_config }}/{{ item }}"
    state: link
    force: yes
  loop:
    - gtk-3.0
    - gtk-4.0