---
- name: Ensure Core directories exist
  ansible.builtin.file:
    path: "{{ xdg_config }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - autostart
    - xdg-desktop-portal

- name: Force-symlink individual Core Files
  ansible.builtin.file:
    src: "{{ repo_system }}/core/xdg-portal/xdg-desktop-portal-kderc"
    dest: "{{ xdg_config }}/xdg-desktop-portal-kderc"
    state: link
    force: yes

# Note: If you add .desktop files to your repo's system/core/autostart folder later,
# add them as individual specific tasks here just like the portal config above!