---
- name: Ensure Core directories exist
  ansible.builtin.file:
    path: "{{ xdg_config }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - autostart
    - xdg-desktop-portal

- name: Symlink Core XDG Portal Configs
  ansible.builtin.file:
    src: "{{ repo_system }}/core/xdg-portal/xdg-desktop-portal-kderc"
    dest: "{{ xdg_config }}/xdg-desktop-portal-kderc"
    state: link
    force: yes

- name: Symlink Autostart Scripts
  ansible.builtin.file:
    src: "{{ repo_system }}/core/autostart/"
    dest: "{{ xdg_config }}/autostart"
    state: link
    force: yes