---
- name: Ensure Desktop directories exist
  ansible.builtin.file:
    path: "{{ xdg_config }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - klassy
    - Kvantum
    - kwin

- name: Symlink Desktop Configurations (Plasma & KWin)
  ansible.builtin.file:
    src: "{{ repo_system }}/desktop/{{ item.folder }}/{{ item.file }}"
    dest: "{{ xdg_config }}/{{ item.file }}"
    state: link
    force: yes
  loop:
    - { folder: "kwin", file: "kwinrc" }
    - { folder: "kwin", file: "kwinrulesrc" }
    - { folder: "klassy", file: "klassyrc" }
    - { folder: "klassy", file: "windecopresetsrc" }
    - { folder: "plasma", file: "breezerc" }
    - { folder: "plasma", file: "kdeglobals" }
    - { folder: "plasma", file: "kglobalshortcutsrc" }
    - { folder: "plasma", file: "plasmarc" }
    - { folder: "plasma", file: "plasmashellrc" }

- name: Symlink Kvantum Theme Folder
  ansible.builtin.file:
    src: "{{ repo_system }}/desktop/Kvantum"
    dest: "{{ xdg_config }}/Kvantum"
    state: link
    force: yes