---
- name: Configure Userspace Dotfiles
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars:
    repo_apps: "{{ ansible_env.HOME }}/Configuration/Apps"
    repo_system: "{{ ansible_env.HOME }}/Configuration/System"
    
    xdg_config: "{{ ansible_env.HOME }}/.config"
    xdg_data: "{{ ansible_env.HOME }}/.local/share"

  tasks:
    - name: Ensure base XDG directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ xdg_config }}"
        - "{{ xdg_data }}"

    # --- APPS ---
    - name: Setup App Configurations
      ansible.builtin.import_tasks: ansible/apps/apps.yaml

    # --- SYSTEM ---
    - name: Setup System Core
      ansible.builtin.import_tasks: ansible/system/core.yaml

    - name: Setup System Appearance
      ansible.builtin.import_tasks: ansible/system/appearance.yaml

    - name: Setup System Desktop Environments
      ansible.builtin.import_tasks: ansible/system/desktop.yaml

    - name: Setup System Flatpak Overrides
      ansible.builtin.import_tasks: ansible/system/flatpak.yaml

    - name: Setup System Hardware
      ansible.builtin.import_tasks: ansible/system/hardware.yaml

    - name: Rebuild KDE Configuration Cache (kbuildsycoca6)
      ansible.builtin.command: kbuildsycoca6
      changed_when: false
      ignore_errors: true

    - name: Rebuild Font Cache
      ansible.builtin.command: fc-cache -f
      changed_when: false
      ignore_errors: true
