---
- name: Ensure App config directories exist
  ansible.builtin.file:
    path: "{{ xdg_config }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - dolphin
    - kate/externaltools
    - kate/lspclient
    - kconf-update
    - konsole
    - krunner
    - spectacle
    - systemsettings

- name: Symlink App Configuration Files
  ansible.builtin.file:
    src: "{{ repo_apps }}/{{ item.src }}"
    dest: "{{ xdg_config }}/{{ item.dest }}"
    state: link
    force: yes
  loop:
    # Dolphin
    - { src: "dolphin/dolphinrc", dest: "dolphinrc" }
    - { src: "dolphin/dolphinui.rc", dest: "dolphin/dolphinui.rc" }
    # Kate
    - { src: "kate/katerc", dest: "katerc" }
    - { src: "kate/externaltools", dest: "kate/externaltools" }
    - { src: "kate/lspclient", dest: "kate/lspclient" }
    # Other KDE Utilities
    - { src: "kconf-update/kconf_updaterc", dest: "kconf_updaterc" }
    - { src: "konsole/konsolerc", dest: "konsolerc" }
    - { src: "krunner/krunnerrc", dest: "krunnerrc" }
    - { src: "spectacle/spectaclerc", dest: "spectaclerc" }
    - { src: "systemsettings/systemsettingsrc", dest: "systemsettingsrc" }